### ISSUE TITLE
incompatibility issues with R, devtools and deplyr

### ISSUE THREAD

**Issue by biodiversity-jen** [ecohealthalliance/lemis#9]
I've encountered a few incompatibility issues over the past 2 weeks while installing the lemis package on two computers running Windows and RStudio. I wanted to share my work process, in case others are having similar challenges and this might help inform package updates.

First, the lemis package isn't compatible with R v.4.0.0. The most recent version that has worked well  for me with the package, and avoided other compatibility issues, is R v.3.6.0 (that said, I haven't tried other more recent versions because of Rtools). This means I also had to downgrade to Rtools35 in order to run devtools.

Second, the latest dplyr upgrade split out tbl_cube as a separate package, which created problems when installing lemis. So I downgraded to deplyr v.0.8.5.

After this, the installation worked smoothly. Thanks for creating this package and sharing the data.

**Comment by eveskew** [comment]
Hi Jennie. Thanks a lot for commenting about your troubles. This is very helpful.

I just upgraded to R 4.0.0 myself (on macOS though) and have gotten a working version of `lemis` going. You're right that `dplyr` v1.0.0 seems to cause us trouble because of the `fstplyr` dependency. My solution there was to downgrade, as you did:

```devtools::install_version("dplyr", version = "0.8.5", repos = "http://cran.us.r-project.org")```

I _think_ your other troubles are related to Windows vs. Mac? At least I had no problems with `lemis` installation with R 4.0.0 and `dplyr` v0.8.5 on a Mac.

I'm guessing you tried this, but did you attempt to install `lemis` with R 4.0.0, Rtools40 (https://cran.r-project.org/bin/windows/Rtools/), and `dplyr` v0.8.5? What happened there?

I'd also just note that the full dataset is available as a CSV file on our Zenodo repository (https://zenodo.org/record/3565869#.XtfkYp5Kjow) if you want to just grab the data manually and not worry about the package.

**Comment by biodiversity-jen** [comment]
Hi Evan,

Nice to hear from you, and thanks again for developing the package. Strange to hear about the discrepancy. I am using a Windows. Updating R to 4.0.0 was my first step when I started getting errors, and I specifically recall receiving the error message that the lemis package wasn’t compatible with 4.0.0. I know very little about the ins and outs of package compatibility, so I’ll leave that to you. But that was before I tried downgrading dplyr (and also probably before the latest update of dplyr was released, since that came out only 5 days ago). If I get a chance I’ll try that combination you asked about, but unfortunately I spent so many hours troubleshooting those issues over the past week that don’t have time to dive in again right now, since I have it finally all working.

Thanks again,
Jennie

[cid:image001.jpg@01D639AF.EB86AC20]<https://defenders.org/>
Jennie Miller
Senior Scientist
Center for Conservation Innovation
Pronouns: she, her, hers

DEFENDERS OF WILDLIFE<https://defenders.org/>
1130 17th Street NW, Washington, DC 20036
TEL: 202.772.0208  FAX: 202.682.1331
Facebook<https://facebook.com/DefendersofWildlife> | Twitter<https://twitter.com/Defenders> | Instagram<https://instagram.com/defendersofwildlife/> | Medium<https://medium.com/wild-without-end>

**Comment by eveskew** [comment]
Thanks to recent updates to `fstplyr`, I *think* we're all good to go again with `lemis`. In other words, it should be operable with R > 4.0.0 and the most recent versions of the various package dependencies. If you're having trouble, I would recommend making sure you've got the most recent version of `fstplyr`:

```devtools::install_github("krlmlr/fstplyr")```

followed by a fresh install of `lemis`:

```devtools::install_github("ecohealthalliance/lemis")```

Hopefully that takes care of most people into the near future...
